### ISSUE TITLE
Doesn't work with fullPage.js

### ISSUE THREAD

**Issue by sssaurabhkv** [chartjs/chartjs-plugin-deferred#1]
This plugin looks great!
But as soon as I included chartjs-plugin-deferred.min.js, all of my existing charts stopped working. Could someone please provide workaround or fix for this issue?

**Comment by sssaurabhkv** [comment]
Update:
Plugin doesn't work with pages where https://github.com/alvarotrigo/fullPage.js is used.
Could someone please provide workaround or fix for this issue?

**Comment by simonbrunel** [comment]
This plugin works **only** with native scrolling but it seems that fullPage.js relies on CSS transforms instead, so unfortunately, this plugin will not work in that case.

**Comment by sssaurabhkv** [comment]
That is sad :( 
This was a great plugin and made our pages look super cool, unfortunately for us that we can't make use of it now :(
Thanks a lot for your prompt reply :)

**Comment by simonbrunel** [comment]
Though, you might want to have a look to the [fullPage.js FAQ](/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions), there is useful information that could help to workaround your issue, especially [this answer](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#lazyload-doesnt-work) suggesting to use the `scrollBar: true` option for fullPage.js.

**Comment by sssaurabhkv** [comment]
I will quickly check it out! Thanks a lot for providing your precious time to us :)

**Comment by sssaurabhkv** [comment]
Thanks a lot! scrollBar:true worked!
Once again, this plugin is amazing!
One doubt, is it possible to rerender the charts everytime(just like chartjs-plugin-deferred is doing the first time) the canvas appears inside the viewport? This would make is supercool!

**Comment by simonbrunel** [comment]
Glad to hear that it works with fullPage.js :)

This plugin doesn't allow to reload the chart once it has appeared on screen and actually, `scroll` listeners are removed as soon as the chart is fully loaded.  You can create a new feature request with details about how you expect it to work, but there is no obvious solution right now, so that might not be implemented anytime soon.

Closing this ticket since a solution has been found for the reported issue.

**Comment by sssaurabhkv** [comment]
Sure, I will create a feature request with required details.
Thanks a ton for your help :)
