### ISSUE TITLE
 Uncaught TypeError: e.defaults.global is undefined

### ISSUE THREAD

**Issue by paglop** [chartjs/chartjs-plugin-deferred#23]
Hi,

First of all thank you very much for ChartJs, it's a great tool that I've been using for more than 10 years.

FYI, I have an error using the compiled and downloaded version at https://github.com/chartjs/chartjs-plugin-deferred/releases/download/v1.0.2/chartjs-plugin-deferred.min.js:
"Uncaught TypeError: e.defaults.global is undefined"
This error disappears if I use it from the sources :
"git clone ... > npm install > npm build ..."

Thanks again.
 
* Chart.js v3.7.0 
* chartjs-plugin-deferred v1.0.2 
* chartjs-plugin-datalabels v2.0.0

**Comment by gregh3269** [comment]
We are waiting for a new release
see https://github.com/chartjs/chartjs-plugin-deferred/pull/21

**Comment by simonbrunel** [comment]
[Version 2.0.0-beta.1](https://github.com/chartjs/chartjs-plugin-deferred/releases/tag/v2.0.0-beta.1) has been released and is compatible with Chart.js v3.
