### ISSUE TITLE
Error with global options

### ISSUE THREAD

**Issue by FlyingLooper** [chartjs/chartjs-plugin-deferred#5]
I was hoping to set some global deferred options with `Chart.defaults.global.plugins.deferred`, but it seems to be undefined.

Chart.js (v2.7.0)
chartjs-plugin-deferred (v0.3.0)

**Comment by simonbrunel** [comment]
That's because v0.3.0 used the [old defaults](/chartjs/chartjs-plugin-deferred/blob/v0.3.0/dist/chartjs-plugin-deferred.js#L28): `Chart.Deferred.defaults`. This will be changed to `Chart.defaults.global.plugins.deferred` in v1.0.0.

**Comment by FlyingLooper** [comment]
I didn't even think to check `Chart.Deferred.defaults`. That works perfectly. Great plugin for a great library. Thanks!

**Comment by simonbrunel** [comment]
[Version 1.0.0](https://github.com/chartjs/chartjs-plugin-deferred/releases/tag/v1.0.0) released!

https://chartjs-plugin-deferred.netlify.com/installation
