### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ticking'

### ISSUE THREAD

**Issue by NoLooseEnds** [chartjs/chartjs-plugin-deferred#6]
> chartjs-plugin-deferred.min.js:10 Uncaught TypeError: Cannot read property 'ticking' of undefined at HTMLDocument.a (chartjs-plugin-deferred.min.js:10)

I'm getting this error in Chrome. 
Plugin version: 0.3.0. 
Chart.js version: 2.7.0
jQuery version: 3.2.1

I'm not that experienced with JS, but please let me know if I need to provide more information.

**Comment by simonbrunel** [comment]
@NoLooseEnds Sorry for the late reply: can you create a jsfiddle like [this one](https://jsfiddle.net/simonbrunel/oetdz8fg/) that reproduces the error? Maybe you can also share the page in which you see that issue. I need to know about the chart and plugin options in order start investigate.

**Comment by NoLooseEnds** [comment]
It could be a bug with Chrome, I did not get the same error in Firefox, and when I tested in Chrome again now, it seems to have disappeared.

The site in question is: http://bit.ly/2gG2shI (using a bit.ly, so google don't index the actual URL)

**Comment by simonbrunel** [comment]
Good to hear that the issue disappeared, don't hesitate to reopen this issue if that happen again.

Your charts look great :)

**Comment by NoLooseEnds** [comment]
Apparently, this bug still exists. Yesterday I tested on a Macbook Pro where I had no problems, but when I got back to my Retina iMac, the bug persisted. The bug is only present in Chrome, latest Firefox is okay.

Chrome Version 62.0.3202.62 (Official Build) (64-bit)

The only difference I can think of is that the MBP is on the latest macOS (10.13), while the iMac is on 10.12.6.

The site is fine when you load it the first time, but when you start scrolling up/down after the chart.js animations loads you get the error.

<img width="1421" alt="error" src="https://user-images.githubusercontent.com/4103531/31987145-2cf962d2-b96b-11e7-9c34-a82cac972a69.png">

**Comment by simonbrunel** [comment]
I can't reproduce this issue in Chrome 62 / Windows 10 (unfortunately, I can't test on macOS). Did you find a bit more about this issue? Might be caused by Chrome extensions, can you test the website in incognito (extensions disabled)?

**Comment by NoLooseEnds** [comment]
Thanks for pointing me in the right direction. It was a greasemonkey/tampermonkey script that triggered the issue. This can stay closed.

Sorry for wasting your time!
